# Generated by Django 2.2.7 on 2019-11-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0, verbose_name='Latitude')),
                ('y', models.FloatField(default=0.0, verbose_name='Longitude')),
                ('unique_squi_id', models.CharField(default='', max_length=200, verbose_name='Unique Squirrel ID')),
                ('Shift', models.CharField(default='', max_length=5)),
                ('Date', models.IntegerField(default=0)),
                ('Age', models.CharField(default='', max_length=100)),
                ('primary_fur_color', models.CharField(default='', max_length=200)),
                ('Location', models.CharField(default='', max_length=100)),
                ('specific_location', models.CharField(default='', max_length=100)),
                ('running', models.BooleanField(default=0.0)),
                ('Chasing', models.BooleanField(default=0.0)),
                ('Climbing', models.BooleanField(default=0.0)),
                ('Eating', models.BooleanField(default=0.0)),
                ('Foraging', models.BooleanField(default=0.0)),
                ('other_activities', models.CharField(default='', max_length=200)),
                ('Kuks', models.BooleanField(default=0.0)),
                ('Quaas', models.BooleanField(default=0.0)),
                ('Moans', models.BooleanField(default=0.0)),
                ('tail_flags', models.BooleanField(default=0.0)),
                ('tail_twitches', models.BooleanField(default=0.0)),
                ('approaches', models.BooleanField(default=0.0)),
                ('indifferent', models.BooleanField(default=0.0)),
                ('runs_from', models.BooleanField(default=0.0)),
            ],
        ),
    ]
