# Generated by Django 2.2.7 on 2019-12-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sight',
            old_name='Chasing',
            new_name='chasing',
        ),
        migrations.RenameField(
            model_name='sight',
            old_name='Climbing',
            new_name='climbing',
        ),
        migrations.RenameField(
            model_name='sight',
            old_name='Eating',
            new_name='eating',
        ),
        migrations.RenameField(
            model_name='sight',
            old_name='Foraging',
            new_name='foraging',
        ),
        migrations.RenameField(
            model_name='sight',
            old_name='Kuks',
            new_name='kuks',
        ),
        migrations.RenameField(
            model_name='sight',
            old_name='Moans',
            new_name='moans',
        ),
        migrations.RenameField(
            model_name='sight',
            old_name='Quaas',
            new_name='quaas',
        ),
        migrations.RemoveField(
            model_name='sight',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='sight',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='sight',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='sight',
            name='Shift',
        ),
        migrations.RemoveField(
            model_name='sight',
            name='unique_squi_id',
        ),
        migrations.AddField(
            model_name='sight',
            name='age',
            field=models.CharField(choices=[('adult', 'ADULT'), ('juvenile', 'JUVENILE')], default='adult', max_length=100),
        ),
        migrations.AddField(
            model_name='sight',
            name='date',
            field=models.IntegerField(default=0, help_text='MMDDYYYY'),
        ),
        migrations.AddField(
            model_name='sight',
            name='location',
            field=models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], default='Ground Plane', max_length=20),
        ),
        migrations.AddField(
            model_name='sight',
            name='shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2),
        ),
        migrations.AddField(
            model_name='sight',
            name='unique_squirrel_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sight',
            name='other_activities',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sight',
            name='primary_fur_color',
            field=models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], default='Black', max_length=100),
        ),
        migrations.AlterField(
            model_name='sight',
            name='specific_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sight',
            name='x',
            field=models.FloatField(default=0.0, max_length=200),
        ),
        migrations.AlterField(
            model_name='sight',
            name='y',
            field=models.FloatField(default=0.0, max_length=200),
        ),
    ]
